# Generated by Django 5.1.7 on 2025-03-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='translation',
            name='input_language',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='translation',
            name='output_language',
            field=models.CharField(max_length=10),
        ),
    ]
